package net.m0ri13.skoh.entity.client;

import net.minecraft.client.render.entity.animation.Animation;
import net.minecraft.client.render.entity.animation.AnimationHelper;
import net.minecraft.client.render.entity.animation.Keyframe;
import net.minecraft.client.render.entity.animation.Transformation;

public class MushroomSkeletonAnimations {


    public static final Animation WALK = Animation.Builder.create(2f).looping()
            .addBoneAnimation("head",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 2.5f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(0.41667f, AnimationHelper.createRotationalVector(2.5f, -2.5f, -2.61f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(1f, AnimationHelper.createRotationalVector(0f, 0f, 2.5f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(1.54167f, AnimationHelper.createRotationalVector(-2.5f, 2.5f, -2.61f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(2f, AnimationHelper.createRotationalVector(0f, 0f, 2.5f),
                                    Transformation.Interpolations.CUBIC)))
            .addBoneAnimation("mushroom_cap",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(1.04167f, AnimationHelper.createTranslationalVector(0f, -0.5f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(2f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC)))
            .addBoneAnimation("mushroom_cap",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(0.70833f, AnimationHelper.createRotationalVector(0f, 2.5f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(1.45833f, AnimationHelper.createRotationalVector(0f, -3.56f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(2f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC)))
            .addBoneAnimation("mushroom_cap",
                    new Transformation(Transformation.Targets.SCALE,
                            new Keyframe(0f, AnimationHelper.createScalingVector(1f, 1f, 1f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(1.04167f, AnimationHelper.createScalingVector(1.1f, 1f, 1f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(2f, AnimationHelper.createScalingVector(1f, 1f, 1f),
                                    Transformation.Interpolations.CUBIC)))
            .addBoneAnimation("left_arm",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(39.51f, -9.48f, -23.87f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(0.41667f, AnimationHelper.createRotationalVector(-40.94f, 10.69f, -14.72f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(1f, AnimationHelper.createRotationalVector(28.89f, -13.41f, -17.95f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(1.54167f, AnimationHelper.createRotationalVector(-48.31f, 15.53f, -19.99f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(2f, AnimationHelper.createRotationalVector(39.51f, -9.48f, -23.87f),
                                    Transformation.Interpolations.CUBIC)))
            .addBoneAnimation("right_arm",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(-25.45f, -11.74f, 4.34f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(0.5f, AnimationHelper.createRotationalVector(42.65f, 11.83f, 16.98f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(1f, AnimationHelper.createRotationalVector(-26.29f, -18.42f, 7.93f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(1.54167f, AnimationHelper.createRotationalVector(37.83f, 15.52f, 16.97f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(2f, AnimationHelper.createRotationalVector(-25.45f, -11.74f, 4.34f),
                                    Transformation.Interpolations.CUBIC)))
            .addBoneAnimation("left_leg",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(-44.97f, -5.3f, 1.77f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(0.45833f, AnimationHelper.createRotationalVector(42.74f, -0.29f, -7.06f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(1.04167f, AnimationHelper.createRotationalVector(-45.19f, 1.76f, -5.3f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(1.5f, AnimationHelper.createRotationalVector(42.7f, -1.99f, -5.22f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(2f, AnimationHelper.createRotationalVector(-44.97f, -5.3f, 1.77f),
                                    Transformation.Interpolations.CUBIC)))
            .addBoneAnimation("right_leg",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(42.7f, 1.99f, 5.22f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(0.45833f, AnimationHelper.createRotationalVector(-50.33f, 2.24f, 5.1f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(1.04167f, AnimationHelper.createRotationalVector(42.7f, 1.99f, 5.22f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(1.5f, AnimationHelper.createRotationalVector(-50.24f, -4.81f, 5.76f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(2f, AnimationHelper.createRotationalVector(42.7f, 1.99f, 5.22f),
                                    Transformation.Interpolations.CUBIC)))
            .addBoneAnimation("body",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, -5f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(0.4167667f, AnimationHelper.createRotationalVector(0f, 10f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(1.0416767f, AnimationHelper.createRotationalVector(0f, -2.5f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(1.5416767f, AnimationHelper.createRotationalVector(0f, 10f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(2f, AnimationHelper.createRotationalVector(0f, -5f, 0f),
                                    Transformation.Interpolations.CUBIC))).build();
    public static final Animation ATTACK = Animation.Builder.create(0.88889f)
            .addBoneAnimation("head",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 2.5f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(0.33333f, AnimationHelper.createRotationalVector(5f, 0f, -2.5f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(0.77778f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(0.88889f, AnimationHelper.createRotationalVector(0f, 2.5f, 0f),
                                    Transformation.Interpolations.CUBIC)))
            .addBoneAnimation("mushroom_cap",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(0.66667f, AnimationHelper.createTranslationalVector(-0.01f, -1f, -0.02f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(0.77778f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC)))
            .addBoneAnimation("mushroom_cap",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(0.33333f, AnimationHelper.createRotationalVector(0.22f, -5f, -2.51f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(0.66667f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(0.77778f, AnimationHelper.createRotationalVector(-7.41f, -2.27f, -2.28f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.88889f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC)))
            .addBoneAnimation("mushroom_cap",
                    new Transformation(Transformation.Targets.SCALE,
                            new Keyframe(0f, AnimationHelper.createScalingVector(1f, 1f, 1f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(0.66667f, AnimationHelper.createScalingVector(1.3f, 1.3f, 1.1f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(0.77778f, AnimationHelper.createScalingVector(1f, 1f, 1f),
                                    Transformation.Interpolations.CUBIC)))
            .addBoneAnimation("left_arm",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(2.5f, -2.5f, -7.61f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(0.22222f, AnimationHelper.createRotationalVector(-90.58f, 22.56f, 4.66f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(0.66667f, AnimationHelper.createRotationalVector(-90.59f, 25.06f, 4.63f),
                                    Transformation.Interpolations.CUBIC)))
            .addBoneAnimation("right_arm",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0.44444f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(0.66667f, AnimationHelper.createTranslationalVector(-0.17f, 0.1f, 1.99f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(0.7963f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(0.88889f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC)))
            .addBoneAnimation("right_arm",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(-4.67f, 7.38f, 2.53f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(0.22222f, AnimationHelper.createRotationalVector(-87.18f, -5.1f, 1.91f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(0.44444f, AnimationHelper.createRotationalVector(-86.9f, -25.07f, 0.85f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(0.66667f, AnimationHelper.createRotationalVector(-86.9f, -25.07f, 0.85f),
                                    Transformation.Interpolations.CUBIC)))
            .addBoneAnimation("left_leg",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(-44.97f, -5.3f, 1.77f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(0.42593f, AnimationHelper.createRotationalVector(30.24f, -0.29f, -7.06f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(0.88889f, AnimationHelper.createRotationalVector(-44.97f, -5.3f, 1.77f),
                                    Transformation.Interpolations.CUBIC)))
            .addBoneAnimation("right_leg",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(42.7f, 1.99f, 5.22f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(0.42593f, AnimationHelper.createRotationalVector(-32.83f, 2.24f, 5.1f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(0.88889f, AnimationHelper.createRotationalVector(42.7f, 1.99f, 5.22f),
                                    Transformation.Interpolations.CUBIC)))
            .addBoneAnimation("body",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(0.33333f, AnimationHelper.createRotationalVector(0f, 22.5f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(0.55556f, AnimationHelper.createRotationalVector(0f, 22.5f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(0.77778f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC)))
            .addBoneAnimation("Bow",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(0.33333f, AnimationHelper.createTranslationalVector(1f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(0.55556f, AnimationHelper.createTranslationalVector(0.1f, -0.42f, 0.11f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(0.66667f, AnimationHelper.createTranslationalVector(0.1f, -0.42f, 0.11f),
                                    Transformation.Interpolations.CUBIC)))
            .addBoneAnimation("Bow",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(0.33333f, AnimationHelper.createRotationalVector(-37.11f, -80.6f, 32.49f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(0.55556f, AnimationHelper.createRotationalVector(-57.11f, -80.6f, 32.49f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(0.66667f, AnimationHelper.createRotationalVector(-57.11f, -80.6f, 32.49f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(0.72222f, AnimationHelper.createRotationalVector(-80.26f, -74.04f, 54.1f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(0.88889f, AnimationHelper.createRotationalVector(-57.11f, -80.6f, 32.49f),
                                    Transformation.Interpolations.CUBIC)))
            .addBoneAnimation("els",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.72222f, AnimationHelper.createRotationalVector(0.72f, -1.64f, -1.75f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("arrow",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(0.27778f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(0.66667f, AnimationHelper.createTranslationalVector(0f, -3f, 3f),
                                    Transformation.Interpolations.CUBIC)))
            .addBoneAnimation("arrow",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0.27778f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC)))
            .addBoneAnimation("arrow",
                    new Transformation(Transformation.Targets.SCALE,
                            new Keyframe(0f, AnimationHelper.createScalingVector(1f, 1f, 1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.74074f, AnimationHelper.createScalingVector(1f, 1f, 1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.75926f, AnimationHelper.createScalingVector(0.1f, 0.1f, 0.1f),
                                    Transformation.Interpolations.LINEAR))).build();
    public static final Animation IDLE = Animation.Builder.create(2f).looping()
            .addBoneAnimation("head",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(2.5f, 2.61f, -2.39f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(1f, AnimationHelper.createRotationalVector(10.22f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(2f, AnimationHelper.createRotationalVector(2.5f, 2.61f, -2.39f),
                                    Transformation.Interpolations.CUBIC)))
            .addBoneAnimation("mushroom_cap",
                    new Transformation(Transformation.Targets.SCALE,
                            new Keyframe(0f, AnimationHelper.createScalingVector(1f, 1f, 1f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(1.125f, AnimationHelper.createScalingVector(1f, 0.95f, 1f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(2f, AnimationHelper.createScalingVector(1f, 1f, 1f),
                                    Transformation.Interpolations.CUBIC)))
            .addBoneAnimation("left_arm",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(13.49f, -7.98f, -7.84f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(1f, AnimationHelper.createRotationalVector(16.24f, -12.78f, -9.25f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(2f, AnimationHelper.createRotationalVector(13.49f, -7.98f, -7.84f),
                                    Transformation.Interpolations.CUBIC)))
            .addBoneAnimation("right_arm",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(-16.34f, -9.95f, 9.09f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(1f, AnimationHelper.createRotationalVector(-13.75f, -7.52f, 8.49f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(2f, AnimationHelper.createRotationalVector(-16.34f, -9.95f, 9.09f),
                                    Transformation.Interpolations.CUBIC)))
            .addBoneAnimation("left_leg",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(2.61f, -2.39f, -2.61f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(1.125f, AnimationHelper.createRotationalVector(2.63f, -7.38f, -2.84f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(2f, AnimationHelper.createRotationalVector(2.61f, -2.39f, -2.61f),
                                    Transformation.Interpolations.CUBIC)))
            .addBoneAnimation("right_leg",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(-4.67f, 7.38f, 2.53f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(1f, AnimationHelper.createRotationalVector(-4.74f, 12.37f, 2.11f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(2f, AnimationHelper.createRotationalVector(-4.67f, 7.38f, 2.53f),
                                    Transformation.Interpolations.CUBIC)))
            .addBoneAnimation("body",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(1f, AnimationHelper.createTranslationalVector(0f, -0.5f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(2f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC)))
            .addBoneAnimation("body",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(1f, AnimationHelper.createRotationalVector(-2.5f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(2f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC))).build();
}
